In [1]:
import pandas as pd

df = pd.read_csv('data/raw/olist_customer360_master_dataset.csv')
print(df.shape)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/olist_customer360_master_dataset.csv'

In [2]:
import pandas as pd

df = pd.read_csv('../data/raw/olist_customer360_master_dataset.csv')
print(df.shape)
df.head()

(99441, 38)

,order_id,customer_id,customer_unique_id,customer_city,customer_state,customer_zip_code_prefix,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,total_items,total_price,total_freight,avg_item_price,total_payment_value,payment_type_main,payment_installments_max,review_score,review_comment_title,review_comment_message
0,2e7a8482f6fb09756ca50c10d7bfc047,08c5351a6aca1c1589a38f244edeee9d,b7d76e111c89f7ebf14761390f0f7d17,boa vista,RR,69309,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,2016-10-18 13:14:51,...,2.0,72.89,63.34,36.445,136.23,credit_card,1.0,1.0,NaN,1 mes de atraso na entrega !!! ultima compra q...
1,e5fa5a7210941f7d56d0208e4e071d35,683c54fc24d40ee9f8a6fc179fd9856c,4854e9b3feff728c13ee5fc7d1547e92,passo fundo,RS,99025,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,NaN,...,1.0,59.50,15.56,59.500,75.06,credit_card,3.0,1.0,NaN,Comprei dois produtos desta loja parceira da l...
2,809a282bbd5dbcabb6f2f724fca862ec,622e13439d6b5a0b486c435618b2679e,009b0127b727ab0ba422f6d9604487c7,sao jose dos campos,SP,12244,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,NaN,...,NaN,NaN,NaN,NaN,40.95,credit_card,2.0,1.0,NaN,MEU PEDIDO NÃO FOI ENTREGUE E NÃO FOI DADA NEN...
3,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,830d5b7aaa3b6f1e9ad63703bec97d23,sao joaquim da barra,SP,14600,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,...,3.0,134.97,8.49,44.990,NaN,NaN,NaN,1.0,NaN,nao recebi o produto e nem resposta da empresa
4,71303d7e93b399f5bcd537d124c0bcfa,b106b360fe2ef8849fbbd056f777b4d5,0eb1ee9dba87f5b36b4613a65074337c,sao paulo,SP,2975,canceled,2016-10-02 22:07:52,2016-10-06 15:50:56,NaN,...,1.0,100.00,9.34,100.000,109.34,credit_card,1.0,1.0,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 38 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   customer_unique_id             99441 non-null  str
 3   customer_city                  99441 non-null  str
 4   customer_state                 99441 non-null  str
 5   customer_zip_code_prefix       99441 non-null  int64
 6   order_status                   99441 non-null  str
 7   order_purchase_timestamp       99441 non-null  str
 8   order_approved_at              99281 non-null  str
 9   order_delivered_carrier_date   97658 non-null  str
 10  order_delivered_customer_date  96476 non-null  str
 11  order_estimated_delivery_date  99441 non-null  str
 12  order_year                     99441 non-null  int64
 13  order_month                    99441 non-null  int64
 14  order_weekday                  99441 non-null  str
 15  delivery_time_days             96476 non-null  float64
 16  estimated_delivery_days        99441 non-null  int64
 17  delivery_delay_days            96476 non-null  float64
 18  is_late_delivery               99441 non-null  bool
 19  product_id                     98666 non-null  str
 20  product_category               97250 non-null  str
 21  product_weight_g               98650 non-null  float64
 22  product_length_cm              98650 non-null  float64
 23  product_height_cm              98650 non-null  float64
 24  product_width_cm               98650 non-null  float64
 25  seller_id                      98666 non-null  str
 26  seller_city                    98666 non-null  str
 27  seller_state                   98666 non-null  str
 28  total_items                    98666 non-null  float64
 29  total_price                    98666 non-null  float64
 30  total_freight                  98666 non-null  float64
 31  avg_item_price                 98666 non-null  float64
 32  total_payment_value            99440 non-null  float64
 33  payment_type_main              99440 non-null  str
 34  payment_installments_max       99440 non-null  float64
 35  review_score                   98673 non-null  float64
 36  review_comment_title           11550 non-null  str
 37  review_comment_message         40775 non-null  str
dtypes: bool(1), float64(13), int64(4), str(20)
memory usage: 28.2 MB

In [4]:
df.isnull().sum().sort_values(ascending=False).head(15)

review_comment_title             87891
review_comment_message           58666
delivery_time_days                2965
order_delivered_customer_date     2965
delivery_delay_days               2965
product_category                  2191
order_delivered_carrier_date      1783
product_length_cm                  791
product_height_cm                  791
product_weight_g                   791
product_width_cm                   791
seller_city                        775
seller_id                          775
seller_state                       775
total_freight                      775
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df[df['seller_id'].isnull()][['order_id','seller_id','seller_city','product_width_cm']].head()

                            order_id seller_id seller_city  product_width_cm
2   809a282bbd5dbcabb6f2f724fca862ec       NaN         NaN               NaN
16  1aecadf4362edaca7fa033e882076c8d       NaN         NaN               NaN
20  620b0acb9258b51defbc51804c5298d5       NaN         NaN               NaN
59  ddaec6fff982b13e7e048b627a11d6da       NaN         NaN               NaN
77  a68ce1686d536ca72bd2dadc4b8671e5       NaN         NaN               NaN

In [7]:
df_clean = df.dropna(subset=['seller_id']).copy()
print(df_clean.shape)

(98666, 38)

In [8]:
df_clean.to_csv('../data/processed/olist_customer360_clean.csv', index=False)
print("Saved!")

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [9]:
df_clean.to_csv('../data/processed/olist_customer360_clean.csv', index=False)
print("Saved!")

Saved!

In [10]:
print(list(df_clean.columns))

['order_id', 'customer_id', 'customer_unique_id', 'customer_city', 'customer_state', 'customer_zip_code_prefix', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'order_year', 'order_month', 'order_weekday', 'delivery_time_days', 'estimated_delivery_days', 'delivery_delay_days', 'is_late_delivery', 'product_id', 'product_category', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm', 'seller_id', 'seller_city', 'seller_state', 'total_items', 'total_price', 'total_freight', 'avg_item_price', 'total_payment_value', 'payment_type_main', 'payment_installments_max', 'review_score', 'review_comment_title', 'review_comment_message']

In [11]:
for col in df_clean.columns:
    print(col)

order_id
customer_id
customer_unique_id
customer_city
customer_state
customer_zip_code_prefix
order_status
order_purchase_timestamp
order_approved_at
order_delivered_carrier_date
order_delivered_customer_date
order_estimated_delivery_date
order_year
order_month
order_weekday
delivery_time_days
estimated_delivery_days
delivery_delay_days
is_late_delivery
product_id
product_category
product_weight_g
product_length_cm
product_height_cm
product_width_cm
seller_id
seller_city
seller_state
total_items
total_price
total_freight
avg_item_price
total_payment_value
payment_type_main
payment_installments_max
review_score
review_comment_title
review_comment_message

In [12]:
with open('../data/processed/column_list.txt', 'w') as f:
    for col in df_clean.columns:
        f.write(col + '\n')
print("Saved column list")

Saved column list

In [13]:
print(df_clean['delivery_time_days'].dtype)
print(df_clean['delivery_time_days'].head(10))

float64
0      NaN
1      NaN
3     54.0
4      NaN
5     23.0
6     24.0
7     35.0
8     30.0
9     27.0
10    10.0
Name: delivery_time_days, dtype: float64

In [14]:
from sqlalchemy import create_engine

# Replace 'yourpassword' with your actual MySQL root password
engine = create_engine("mysql+pymysql://root:yourpassword@localhost/customer360")

df_clean.to_sql('customers360', con=engine, if_exists='replace', index=False)
print("Loaded into MySQL!")

OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [15]:
engine = create_engine("mysql+pymysql://root:Subham2026sql@localhost/customer360")

In [16]:
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:Subham@2026@localhost/customer360")

df_clean.to_sql('customers360', con=engine, if_exists='replace', index=False)
print("Loaded into MySQL!")

OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '2026@localhost' ([Errno 11003] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [17]:
engine = create_engine("mysql+pymysql://root:Subham%402026@localhost/customer360")

In [18]:
engine = create_engine("mysql+pymysql://root:Subham%402026@127.0.0.1:3306/customer360")

In [19]:
df_clean.to_sql('customers360', con=engine, if_exists='replace', index=False)
print("Loaded into MySQL!")

Loaded into MySQL!

In [20]:
import pandas as pd

df_rfm = pd.read_csv(r"C:\Users\pattn\OneDrive\Desktop\Customer-360-Next-Best-Action\Data\Raw\olist_customer_level_rfm.csv")
df_rfm.to_sql('customer_rfm', con=engine, if_exists='replace', index=False)
print("RFM table loaded into MySQL!")

RFM table loaded into MySQL!

In [21]:
df_clv = pd.read_csv(r"C:\Users\pattn\OneDrive\Desktop\Customer-360-Next-Best-Action\Data\Raw\olist_customer_clv.csv")
df_clv.to_sql('customer_clv', con=engine, if_exists='replace', index=False)
print("CLV table loaded into MySQL!")

CLV table loaded into MySQL!

In [22]:
df_nba = pd.read_csv(r"C:\Users\pattn\OneDrive\Desktop\Customer-360-Next-Best-Action\Data\Raw\olist_next_best_action.csv")
df_nba.to_sql('next_best_action', con=engine, if_exists='replace', index=False)
print("NBA table loaded into MySQL!")

NBA table loaded into MySQL!